### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by sebastianbergmann** [phpspec/prophecy-phpunit#22]
Is there anything that prevents a new release to be tagged? I will release PHPUnit 9.1 on Friday, April 3, 2020, and it would be great if the new version would be available then.

**Comment by stof** [comment]
Well, will there be other BC breaks in PHPUnit 9 before the release ? I'd rather avoid tagging a release which would not work with the released version of PHPUnit.

**Comment by sebastianbergmann** [comment]
There will be no more changes related to this before PHPUnit 9.1.0 is tagged.

**Comment by Jean85** [comment]
PHPUnit 9.1 has been tagged, you should release this too before receiving an horde of new issues :smile:

**Comment by localheinz** [comment]
@stof 

Anything holding up a new release?

**Comment by stof** [comment]
The release is now done.

**Comment by localheinz** [comment]
Thank you, @stof!
