### ISSUE TITLE
Mark `v2.0.0` as `latest release` on GitHub

### ISSUE THREAD

**Issue by jdreesen** [phpspec/prophecy-phpunit#24]
Currently, GitHub says `1.1.0` is the `latest release`.

![grafik](https://user-images.githubusercontent.com/424602/86000584-04240780-ba0e-11ea-99c4-98d21a0e662d.png)

![grafik](https://user-images.githubusercontent.com/424602/86000664-21f16c80-ba0e-11ea-8c35-f6e1b2dade80.png)

**Comment by stof** [comment]
Done. I forgot to create the github release when creating the tag.
