### ISSUE TITLE
Mocks do not fail immedately on unexpected calls

### ISSUE THREAD

**Issue by Jean85** [phpspec/prophecy-phpunit#27]
I've migrated to this trait since PHPUnit deprecated its integration with Prophecy.

I've struggled a little since then, but I've now found the root of my issue: **mocks are not failing immediately** as before.

This is a reproducer:

```php
<?php

declare(strict_types=1);

class MockRegressionTest extends \PHPUnit\Framework\TestCase
{
    use ProphecyTrait;

    public function test(): void
    {
        $prophecy = $this->prophesize(\PHPUnit\Framework\TestSuite::class);
        $prophecy->addTestFile('foo.php')
            ->shouldBeCalledOnce();

        $prophecy->reveal()
            ->addTestFile('bar.php'); // should fail here

        $this->fail('If we got here, we have some trouble'); // goes on and fails here
    }
}
```

Test should fail immediately when calling the method with the wrong argument, but it doesn't. This leads to the mock returning `null` and either failing with a `TypeError` or going further, making the test failure a lot harder to debug.

Copying this reproducer into a PHPSpec test gets the right behavior.

Thanks to @DonCallisto for the help debugging this issue.

**Comment by Jean85** [comment]
I'm investigating further, and it seems that this is in reality due to https://github.com/phpspec/prophecy/issues/457 and related to https://github.com/phpspec/prophecy/pull/441

**Comment by stof** [comment]
Closing in favor of https://github.com/phpspec/prophecy/issues/508
