### ISSUE TITLE
Migrate to GH Actions ?

### ISSUE THREAD

**Issue by jrfnl** [phpspec/prophecy-phpunit#34]
I'm looking to create a PR to address https://github.com/Yoast/PHPUnit-Polyfills/issues/62 and just noticed that the CI is still on travis-ci.org, which (for the most part) is no longer functional.

@stof Would it be okay if I migrate the CI checks to GitHub Actions to get them running again ?

**Comment by stof** [comment]
@jrfnl yes

**Comment by jrfnl** [comment]
PR #35 has been opened to address this.
