### ISSUE TITLE
Unable to install on PHP 8.2.1? 

### ISSUE THREAD

**Issue by the-zalox** [phpspec/prophecy-phpunit#44]
Problem 1
    - phpspec/prophecy v1.15.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.1) does not satisfy that requirement.
    - phpunit/phpunit 9.5.20 requires phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[v1.15.0].
    - phpunit/phpunit is locked to version 9.5.20 and an update of this package was not requested.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require phpspec/prophecy-phpunit:*" to figure out if any version is installable, or "composer require phpspec/prophecy-phpunit:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by jdreesen** [comment]
Why is it trying to install `phpspec/prophecy v1.15.0`? There's `v1.16.0`, which is compatible to PHP 8.2.

What was the exact command you used?
Does it help to add `-W` (`--update-with-all-dependencies`)

If that doesn't help, what does `composer why phpspec/prophecy` say?

**Comment by stof** [comment]
The issue is that you use PHPUnit 10, which is not supported yet. Work for that is in progress (but I won't manage to complete it before my vacation week that starts tomorrow so you'll need to wait a but).
Stick to PHPUnit 9.x for now.

**Comment by TheLevti** [comment]
Any update on this?

**Comment by davidrans** [comment]
Looks like PHPUnit 10 support has been added on `master`. Any chance we could get a new release soon?

**Comment by TheLevti** [comment]
Master is broken as well as it requires a version of phpspec/prophecy that does not exist yet. Had to fork it out and fix master and then use dev-master until maintainer does a proper release.

**Comment by stof** [comment]
@TheLevti you don't need to require `dev-master`. prophecy has a branch alias so its dev-master version fulfills the existing requirement.
However, when you want to use the dev version, you indeed have to allow composer to use the dev version of prophecy.
