### ISSUE TITLE
PHPUnit 10 Support

### ISSUE THREAD

**Issue by luchaninov** [phpspec/prophecy-phpunit#47]
PHPUnit 10 was released 5 days ago
https://github.com/sebastianbergmann/phpunit/releases/tag/10.0.0

It's not possible to upgrade because of dependency in composer.json `"require": { ... "phpunit/phpunit":"^9.1" ... }`
https://github.com/phpspec/prophecy-phpunit/blob/master/composer.json#L19

**Comment by jdreesen** [comment]
#45
