### ISSUE TITLE
Argument shortcut method on the TestCase

### ISSUE THREAD

**Issue by adrienbrault** [phpspec/prophecy-phpunit#5]
What would you think about adding an `arg()` method or `arg` property on the test case that would return a `Prophecy\Argument` instance ?

I did it in https://github.com/hautelook/frankenstein#prophecy-arguments , but maybe it would be useful for everyone using `prophecy-phpunit`.

**Comment by stof** [comment]
Closing this old issue as this library is abandoned in favor of PHPUnit built-in support anyway.
