### ISSUE TITLE
PhpUnit 10 support

### ISSUE THREAD

**Issue by zrajic** [phpspec/prophecy-phpunit#54]
Hello,

When could we expect new patch with PhpUnit 10.x support? Thank you!

cc @stof

**Comment by marcreichel** [comment]
+1

**Comment by christiankaemper** [comment]
+1

**Comment by sidler** [comment]
+1

**Comment by igorkosteski** [comment]
+1

**Comment by Havrin** [comment]
out of curiosity: Is there still a blocker or was https://github.com/phpspec/prophecy-phpunit/pull/45 the last one? If so, why does it take so long just to tag a version? Thanks in advance

**Comment by rdanklof** [comment]
+1

**Comment by Wick96** [comment]
+1

**Comment by zrajic** [comment]
@stof any news?

**Comment by gnutix** [comment]
+1

**Comment by AndriiLazarenko** [comment]
Up

**Comment by dunglas** [comment]
Could it be possible to make the `prophesize()` method static? PHPUnit 10 deprecated non-static data providers, and creating mocks in data providers is very common. PHPUnit made its own `createMock()` and `createStub()` methods static in v10, likely for this reason.

**Comment by tPl0ch** [comment]
I can only recommend using an AI bot to convert PHPSpec notations to PHPUnit mocking / stubbing notations, and then remove the dependency on this library.

**Comment by stof** [comment]
@dunglas As Prophecy does not have separate concept of stubs (for which there is no need to check expectations) and mocks (for which we need to check that at the end of the test), we cannot make the method static as that would break things (doubles created in a data provider would not be properly checked at the end of the tests)

**Comment by zrajic** [comment]
@stof is there any news on this? last issue was merged on 21. of april and now we are waiting for new version that should support PhpUnit 10. Please can we do something about this and are there any blockers for new version of phpunit

**Comment by jg-development** [comment]
can this plz be merged?

**Comment by Jean85** [comment]
I'm using dev-master successfully since April, can we tag a 2.2.0 to that the support is official?

**Comment by keradus** [comment]
@stof , as prophecy was released, maybe we can release head of main branch here as well?

**Comment by stof** [comment]
@keradus the work is in progress right now.
