### ISSUE TITLE
PHPUnit 11 deprecations

### ISSUE THREAD

**Issue by Jean85** [phpspec/prophecy-phpunit#60]
I've already opened #59 + phpspec/prophecy#616 to allow PHPUnit 11 compatibility, but I've already found that the `ProphecyTrait` triggers deprecations in that case. It triggers 2 deprecations for each test execution, so that A LOT of noise, especially if data providers are involved.

As already (wrongly) reported in https://github.com/sebastianbergmann/phpunit/issues/5693#issuecomment-1926822872,

> [...] the causes are the `@postCondition` and `@after` annotations here:
> 
> * https://github.com/phpspec/prophecy-phpunit/blob/29f8114c2c319a4308e6b070902211e062efa392/src/ProphecyTrait.php#L57-L60
> 
> * https://github.com/phpspec/prophecy-phpunit/blob/29f8114c2c319a4308e6b070902211e062efa392/src/ProphecyTrait.php#L75-L78

Those annotations can be replaced by attributes since PHPUnit 10.0.0, or you can replace it with using the `assertPostCondition` and `tearDown` methods.

So, I'm asking, how should we proceed? I see 3 possibilities:
 * we switch to the `assertPostCondition` and `tearDown` methods, so that we don't drop support for older versions (but we mess with the inheritance chain of those methods, and the user could inadvertently deactivate that code path)
 * we switch to attributes, dropping support for PHPUnit 9
 * we do a mix, adding the methods but invoking the sub-methods only for PHPUnit 9, leaving the rest to the attributes

WDYT? ping @stof

**Comment by stof** [comment]
We should not use `assertPostCondition` and `tearDown` because that would mean that any TestCase using the trait would then have to be careful to call our method when they use those extension points. That's precisely why PHPUnit added the feature to allow using arbitrary methods.

@sebastianbergmann would it work to apply both the attribute and the phpdoc tag as a way to support PHPUnit 9 and 11 at the same time, or would this register the methods twice for PHPUnit 10+ ?

**Comment by Jean85** [comment]
IMO using both would could trigger the deprecations anyway, so it would not solve our issue...

**Comment by stof** [comment]
Well, that's what I'd like to confirm. It would be great if PHPUnit could support the case of applying both as a way to support multiple versions (basically ignoring the phpdoc tag if the attribute is applied).

**Comment by stof** [comment]
I'm closing this issue as the solution for those deprecations is found. Please update #59 to add the attribute without removing the annotation.
